"""add documeny_type and other missing columns to payment table

Revision ID: 2d3cd9888249
Revises: a20d48751b92
Create Date: 2026-03-29 17:49:23.755820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3cd9888249'
down_revision = 'a20d48751b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('increment_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('increment_history_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('due_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('paid_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_date', sa.DATE(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('due_date')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('status')
        batch_op.drop_column('due_amount')
        batch_op.drop_column('document_type')

    with op.batch_alter_table('increment_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('increment_history_ibfk_1'), 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###
