"""add resignation email fields

Revision ID: 71fae66f1965
Revises: c4774f13c0ef
Create Date: 2026-02-24 17:07:58.665372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fae66f1965'
down_revision = 'c4774f13c0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resignation_email_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resignation_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('resignation_datetime')
        batch_op.drop_column('resignation_email_content')

    # ### end Alembic commands ###
