"""deleted intern payment table

Revision ID: 75bd595173f5
Revises: 2d3cd9888249
Create Date: 2026-03-30 13:13:56.977240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75bd595173f5'
down_revision = '2d3cd9888249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intern_payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intern_payments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('intern_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('paid_amt', mysql.FLOAT(), nullable=True),
    sa.Column('due_amount', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('payment_date', sa.DATE(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['intern_documents.id'], name=op.f('intern_payments_ibfk_2')),
    sa.ForeignKeyConstraint(['intern_id'], ['interns.id'], name=op.f('intern_payments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
