"""update payment model with new fields

Revision ID: 932475fa0b2b
Revises: 74a2c66c4278
Create Date: 2026-02-25 15:43:43.975378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '932475fa0b2b'
down_revision = '74a2c66c4278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_amt', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overdue_amount', sa.Float(), nullable=True))
        batch_op.drop_column('due_date')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('status')
        batch_op.drop_column('notes')
        batch_op.drop_column('created_at')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('notes', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_method', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DATE(), nullable=True))
        batch_op.drop_column('overdue_amount')
        batch_op.drop_column('paid_amt')

    # ### end Alembic commands ###
