"""add relieving_date to employee

Revision ID: 93bbf995ec40
Revises: 71fae66f1965
Create Date: 2026-02-25 11:29:30.932768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bbf995ec40'
down_revision = '71fae66f1965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relieving_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('relieving_date')

    # ### end Alembic commands ###
